# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

env:
  global:
    - POLR_API_KEY=1234
    - POLR_URL=https://polr.eample.com

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  provider: pypi
  user: kylie.a
  password:
    secure: vEHoOhAR+MJFJkqJp+7YcTXSACknAs7P0eFJwDsyAn2K+BR9sELEBPEcmWk7QnviVapcUXJG4rkzKNqHZM4frmsGyUHwIq4uS72CveOUZeHoaXSpV3Tg+s4pE2E4L6YjqEnBut0Uwdv3sCQmk3HUvcV6ytQzS8FJV3Sg9TuJC2fkteADLKXBs0c/nas3IbIenD/PzicptWFKZHbstyDULxfLT/zPVRFEXSnKstQpeEnXYYttZ/6fnVpWX21WTwf7B+GFsjHBNafniK+bnz6ypz31DjcjT+5UoDD588Bp+9b67qDWviKwgBU6RtRewPokBGYsbZzi0CZOPiLDrYeNH6GKsEzz6bPrV3atLQSNJE24xEtxN1f09OKKXphKebSmnvIzYl1wUUEKMT/OE1zbc6I0q6vRoVbER69evgrEXK8GWkHqH/LQVkTi7KsphAjLQvR1VzM95WRw36e0iOLrhQux+2LdBC6FuZo7vh9n3/vbmWdiIiA7FK/Tk0Mwr0ySZ3+WaruPWjy4FNb+HDeBnQx0UydNbX/Fa9qwWq5+oekP4zWnxVu60jsQEQhYmtNUKfIPc2nBbDR18HHmNzAd4PC9O4RdiqkMe5Bw0QyZhHAaJMPuLO8xFqH9yZQHJjhKyAt2sauLzSa9HBmcLzAy7ZOS/Jr5P4851WpnstOl3dA=
  on:
    tags: true
